import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'John',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'User',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],

  products: [
    {
      name: 'God Of War Ragnarok',
      slug: 'God Of War Ragnarok',
      category: 'PS4',
      image: '/images/gow.jpg',
      price: 50,
      brand: 'PS4',
      rating: 4.5,
      numReviews: 5,
      countInStock: 10,
      description: 'Together, Kratos and Atreus venture deep into the Nine Realms in search of answers as Asgardian forces prepare for war. Along the way they will explore stunning, mythical landscapes, gather allies from across the realms and face fearsome enemies in the form of Norse gods and monsters. Play it on PlayStation 4',
    },
    {
      name: 'Spiderman',
      slug: 'Spiderman',
      category: 'PS4',
      image: '/images/spiderman.jpg',
      price: 40,
      brand: 'PS4',
      rating: 4.2,
      numReviews: 5,
      countInStock: 10,
      description: 'When a new villain threatens Marvel New York, Peter Parker and Spiderman worlds collide. To save the city and those he loves, he must rise up and be greater',
    },
    {
      name: 'The Last Of Us',
      slug: 'The Last Of Us',
      category: 'PS4',
      image: '/images/TLOU.jpg',
      price: 45,
      brand: 'PS4',
      rating: 4.5,
      numReviews: 5,
      countInStock: 10,
      description: 'For Joel, every day is about looking out for number one. But when he\'s charged with escorting teenager Ellie in search of resistance group the Fireflies, they\'ll find their will to survive pushed to the limit.',
    },
    {
      name: 'Fifa 23',
      slug: 'Fifa 23',
      category: 'PS4',
      image: '/images/fifa.jpg',
      price: 50,
      brand: 'PS4',
      rating: 4.5,
      numReviews: 5,
      countInStock: 10,
      description: 'FIFA 23 PROVIDES MORE TRUE FOOTBALL ANIMATIONS THAN EVER BEFORE, Experience next-gen FIFA 23 HyperMotion2 Technology, FIFA World Cup, and for the first time cross play comes to FIFA 23 Play The World\'s Game with 19, 000+ players, 700+ teams, 100+ stadiums, 30+ leagues, and the world\'s biggest competitions in FIFA 23. Enjoy a more true-to - life football experience with new gameplay features in FIFA 23 Play it on PlayStation 4',
    },
    {
      name: 'GTA 5',
      slug: 'GTA 5',
      category: 'PS4',
      image: '/images/gta.jpg',
      price: 20,
      brand: 'PS4',
      rating: 4.8,
      numReviews: 5,
      countInStock: 10,
      description: 'Enter the lives of three very different criminals, Michael, Franklin and Trevor, as they risk everything in a series of daring and dangerous heists that could set them up for life.',
    },
    {
      name: 'Bloodborne',
      slug: 'Bloodborne',
      category: 'PS4',
      image: '/images/Bloodborne.jpg',
      price: 30,
      brand: 'PS4',
      rating: 3.4,
      numReviews: 5,
      countInStock: 10,
      description: 'Bloodborne on PS4 Face your fears in this dangerous new world, where danger, death and madness lurk around every corner. in Bloodborne on PlayStation 4',
    },
  ],
};

export default data;
